//! The chat-template renderer against real checkpoints.
//!
//! `tests/templates/*.jinja` are verbatim `tokenizer.chat_template`
//! strings, read out of the metadata of real GGUFs in `models/` and not
//! paraphrased. Fifteen families are covered, chosen so that every shape
//! the deleted marker-sniffer got wrong is represented: Mistral's
//! `[INST] … [/INST]` (which matched none of its six markers and served
//! as `user: …`), Phi-3 and Phi-4-mini, DeepSeek-R1's `<think>` framing,
//! Yi, TinyLlama, SmolLM2, Qwen 1.5-MoE / 2.5 / 3, Llama 3.1 and 3.2,
//! and gemma 2 / 3 / 4.
//!
//! Three layers:
//!
//! * `real_templates_render_byte_for_byte_like_the_reference_engines`
//!   is the one that can catch a wrong prompt. Each template has a
//!   `.expected` golden produced by **real jinja2**, configured the way
//!   HuggingFace and llama.cpp configure it, by
//!   `scripts/chat_template_goldens.py`. The goldens come from a
//!   different implementation than the code under test, so a regression
//!   here cannot rewrite its own expectations. It found one: minijinja
//!   defaults `trim_blocks` / `lstrip_blocks` to false and both
//!   reference engines set them true for chat templates, which put
//!   thirteen bytes of stray blank line into every TinyLlama prompt.
//! * `every_checked_in_template_compiles_and_renders` is the cheap
//!   smoke test over the same corpus.
//! * `sweep_every_local_gguf_template` is `#[ignore]`d because it needs
//!   the checkpoints themselves. It opens every GGUF under `models/`
//!   (or `$FRINK_TEST_MODELS_DIR`), pulls each one's real template, and
//!   renders a fixed three-turn conversation through it. That is how
//!   the compile/render coverage claim in
//!   `docs/plans/llama-cpp-parity-push.md` was measured; re-run it with
//!   `cargo test -p frink-models --test chat_template_real_gguf -- --ignored --nocapture`.

mod common;
use common::collect_gguf;
use frink_models::chat_template::{ChatTemplate, RenderOptions};
use serde_json::json;

/// The number of real families pinned here. Asserted rather than
/// counted so that deleting a template is a failing test, not a quietly
/// smaller sweep.
const TEMPLATE_COUNT: usize = 15;

fn templates_dir() -> std::path::PathBuf {
    std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/templates")
}

fn checked_in_templates() -> Vec<(String, String)> {
    let dir = templates_dir();
    let mut out = Vec::new();
    for entry in std::fs::read_dir(&dir).expect("tests/templates") {
        let path = entry.unwrap().path();
        if path.extension().and_then(|e| e.to_str()) != Some("jinja") {
            continue;
        }
        let stem = path.file_stem().unwrap().to_str().unwrap().to_string();
        out.push((stem, std::fs::read_to_string(&path).unwrap()));
    }
    out.sort();
    assert_eq!(
        out.len(),
        TEMPLATE_COUNT,
        "expected {TEMPLATE_COUNT} real GGUF templates in {dir:?}"
    );
    out
}

fn conversation() -> Vec<serde_json::Value> {
    vec![
        json!({"role": "user", "content": "What is the capital of France?"}),
        json!({"role": "assistant", "content": "Paris."}),
        json!({"role": "user", "content": "And of Italy?"}),
    ]
}

/// The second scenario the goldens pin: a system turn, which several
/// families fold into the first user message and two refuse outright.
fn system_conversation() -> Vec<serde_json::Value> {
    vec![
        json!({"role": "system", "content": "Answer with one word."}),
        json!({"role": "user", "content": "What is the capital of France?"}),
    ]
}

fn opts() -> RenderOptions {
    let mut extra = serde_json::Map::new();
    // Llama-3.x bakes today's date into its system header through
    // `strftime_now` unless the caller defines `date_string`. Pin it, or
    // the golden expires at midnight.
    extra.insert("date_string".into(), json!("26 Jul 2024"));
    RenderOptions {
        add_generation_prompt: true,
        bos_token: Some("<s>".into()),
        eos_token: Some("</s>".into()),
        extra,
        ..Default::default()
    }
}

#[test]
fn every_checked_in_template_compiles_and_renders() {
    for (stem, src) in checked_in_templates() {
        let tmpl = ChatTemplate::from_jinja(&src)
            .unwrap_or_else(|e| panic!("{stem} did not compile: {e}"));
        let out = tmpl
            .render(&conversation(), &opts())
            .unwrap_or_else(|e| panic!("{stem} did not render: {e}"));
        assert!(
            out.contains("And of Italy?"),
            "{stem} dropped the last user turn:\n{out}"
        );
    }
}

/// Byte-for-byte against goldens generated by real jinja2.
///
/// Regenerate with `python3 scripts/chat_template_goldens.py` after a
/// *deliberate* change, and never by pasting what the failure printed:
/// the whole value of the file is that a second implementation produced
/// it. A `.raises` golden instead of a `.expected` one means the
/// template refuses that conversation shape, and frink must surface the
/// refusal rather than invent a framing for it.
#[test]
fn real_templates_render_byte_for_byte_like_the_reference_engines() {
    let dir = templates_dir();
    let mut compared = 0usize;
    let mut refusals = 0usize;
    let mut wrong = Vec::new();

    for (stem, src) in checked_in_templates() {
        let tmpl = ChatTemplate::from_jinja(&src)
            .unwrap_or_else(|e| panic!("{stem} did not compile: {e}"));
        for (suffix, messages) in [("", conversation()), (".system", system_conversation())] {
            let golden = dir.join(format!("{stem}{suffix}.expected"));
            let raises = dir.join(format!("{stem}{suffix}.raises"));
            let rendered = tmpl.render(&messages, &opts());
            match (golden.exists(), raises.exists()) {
                (true, false) => {
                    let want = std::fs::read_to_string(&golden).unwrap();
                    match rendered {
                        Ok(got) if got == want => compared += 1,
                        Ok(got) => {
                            wrong.push(format!("{stem}{suffix}\n  want {want:?}\n  got  {got:?}"))
                        }
                        Err(e) => wrong.push(format!(
                            "{stem}{suffix}: refused, reference renders it: {e}"
                        )),
                    }
                }
                (false, true) => {
                    let message = std::fs::read_to_string(&raises).unwrap();
                    match rendered {
                        Ok(got) => wrong.push(format!(
                            "{stem}{suffix}: rendered {got:?}, reference raises {message:?}"
                        )),
                        Err(e) => {
                            // The template's own `raise_exception` text has
                            // to reach the caller, or a refusal is
                            // indistinguishable from an engine bug.
                            assert!(
                                e.to_string().contains(message.trim()),
                                "{stem}{suffix}: refusal lost the template's message\n  want {message:?}\n  got  {e}"
                            );
                            refusals += 1;
                        }
                    }
                }
                _ => panic!(
                    "{stem}{suffix}: no golden -- run python3 scripts/chat_template_goldens.py"
                ),
            }
        }
    }

    assert!(
        wrong.is_empty(),
        "render disagrees with jinja2:\n{}",
        wrong.join("\n")
    );
    assert_eq!(compared + refusals, TEMPLATE_COUNT * 2);
    assert!(
        refusals >= 2,
        "the refusing templates stopped refusing ({refusals})"
    );
}

/// The specific regression the goldens caught, kept as its own test so
/// the reason is not buried in a corpus loop.
///
/// TinyLlama's real template does not use `{%- … -%}` whitespace
/// control, so it depends on `trim_blocks` / `lstrip_blocks` being on --
/// which HuggingFace and llama.cpp both do for chat templates and
/// minijinja does not by default. Without them every turn gained blank
/// lines the checkpoint was never trained on.
#[test]
fn whitespace_control_matches_huggingface_and_llama_cpp() {
    let src = std::fs::read_to_string(templates_dir().join("tinyllama-1.1b-chat.jinja")).unwrap();
    let out = ChatTemplate::from_jinja(&src)
        .unwrap()
        .render(&conversation(), &opts())
        .unwrap();
    assert_eq!(
        out,
        concat!(
            "<|user|>\nWhat is the capital of France?</s>\n",
            "<|assistant|>\nParis.</s>\n",
            "<|user|>\nAnd of Italy?</s>\n",
            "<|assistant|>\n",
        ),
        "trim_blocks/lstrip_blocks regressed"
    );
    assert!(
        !out.starts_with('\n'),
        "leading blank line is back: {out:?}"
    );
    assert!(
        !out.contains("\n\n"),
        "blank line inside the prompt: {out:?}"
    );
}

/// Every template must be *evaluated*, never sniffed. This pins the
/// specific regression, now against the actual file it happened to:
/// Mistral-7B-Instruct-v0.2's real template matches none of the six
/// markers the old `ChatTemplate::detect` looked for, so a Mistral
/// checkpoint was served `user: …` plain lines, a framing it has never
/// seen.
#[test]
fn a_template_with_no_recognisable_marker_still_renders_correctly() {
    let src =
        std::fs::read_to_string(templates_dir().join("mistral-7b-instruct-v0.2.jinja")).unwrap();
    let out = ChatTemplate::from_jinja(&src)
        .unwrap()
        .render(&conversation(), &opts())
        .unwrap();
    assert!(!out.contains("user: "), "sniffed into Plain lines: {out:?}");
    // `{{ bos_token }}` and `{{ eos_token }}` come from the vocabulary
    // the caller passed in, not from a renderer that hardcoded `</s>`.
    assert_eq!(
        out,
        "<s>[INST] What is the capital of France? [/INST]Paris.</s>[INST] And of Italy? [/INST]"
    );
}

/// The other half of "evaluated, never sniffed": a checkpoint that
/// carries no template at all is the one case that *is* a fallback, and
/// it must be llama.cpp `--jinja`'s ChatML default rather than a guess.
/// `models/olmoe-1b-7b-0924-q4_0.gguf` is the local checkpoint in that
/// state.
#[test]
fn a_checkpoint_with_no_template_falls_back_to_chatml_not_to_a_guess() {
    let t = ChatTemplate::from_gguf_metadata(None, Some("olmoe"), false, true);
    assert!(!t.is_jinja());
    let out = t.render(&conversation(), &opts()).unwrap();
    assert_eq!(
        out,
        concat!(
            "<|im_start|>user\nWhat is the capital of France?<|im_end|>\n",
            "<|im_start|>assistant\nParis.<|im_end|>\n",
            "<|im_start|>user\nAnd of Italy?<|im_end|>\n",
            "<|im_start|>assistant\n",
        )
    );
    // An empty-string template is the same absence, not a template that
    // renders to nothing.
    assert!(!ChatTemplate::from_gguf_metadata(Some("   "), Some("olmoe"), false, true).is_jinja());
    // No real vocabulary for markers to live in ⇒ role-labelled lines.
    assert_eq!(
        ChatTemplate::from_gguf_metadata(None, Some("ferroxtest"), true, true)
            .render(&[json!({"role": "user", "content": "hi"})], &opts())
            .unwrap(),
        "user: hi"
    );
}

#[test]
#[ignore = "needs the real GGUF checkpoints in models/"]
fn sweep_every_local_gguf_template() {
    let root = std::env::var("FRINK_TEST_MODELS_DIR").unwrap_or_else(|_| "models".to_string());
    let mut files = Vec::new();
    collect_gguf(std::path::Path::new(&root), &mut files);
    assert!(!files.is_empty(), "no GGUFs under {root}");

    let mut with_template = 0;
    let mut failures = Vec::new();
    for path in &files {
        let Ok(file) = frink_gguf::ShardedGguf::open(path.to_str().unwrap()) else {
            continue;
        };
        let Some(src) = frink_gguf::TensorSource::metadata_str(&file, "tokenizer.chat_template")
            .filter(|t| !t.trim().is_empty())
        else {
            println!("{}: no chat template", path.display());
            continue;
        };
        with_template += 1;
        match ChatTemplate::from_jinja(src).and_then(|t| t.render(&conversation(), &opts())) {
            Ok(out) => println!(
                "{}: OK ({} bytes)\n---\n{out}\n---",
                path.display(),
                out.len()
            ),
            Err(e) => failures.push(format!("{}: {e}", path.display())),
        }
    }
    println!("{with_template} templates, {} failures", failures.len());
    assert!(failures.is_empty(), "{failures:#?}");
}
