//! Generic-MoE routing-bias coverage, checked against llama.cpp itself.
//!
//! `tests/fixtures/dots1_tiny.gguf` is a 2-layer, 32-wide, 6-expert
//! `dots1` checkpoint generated by `scripts/make_dots1_fixture.py`
//! (fixed seed, byte-stable). `dots1` is the smallest architecture on
//! llama.cpp's *generic* MoE path that carries
//! `blk.N.exp_probs_b.bias` — DeepSeek-V3's aux-loss-free expert
//! selection bias. The same tensor appears on ernie4_5-moe,
//! bailingmoe2, exaone-moe, hunyuan-moe and afmoe, which is why one
//! validated implementation is worth a fixture.
//!
//! The fixture also carries a leading dense layer, a shared expert,
//! `expert_weights_norm = true` and `expert_weights_scale = 2.5`, so the
//! two hparams the bias interacts with are in the comparison too.
//!
//! `GOLDEN_LOGITS` was produced by running **llama.cpp's own** dots1
//! implementation over that same file
//! (`scripts/gptoss_reference_logits.cpp`, linked against a real
//! `libllama`), not by re-reading a spec and not by ferrox checking
//! itself.
//!
//! Regenerating (both halves must be redone together if the fixture
//! changes):
//!
//! ```text
//! PYTHONPATH=$LLAMA/gguf-py python3 scripts/make_dots1_fixture.py \
//!     crates/ferrox-models/tests/fixtures/dots1_tiny.gguf
//! clang++ -std=c++17 -O2 scripts/gptoss_reference_logits.cpp \
//!     -I$LLAMA/include -I$LLAMA/ggml/include -L$BUILD/bin -lllama \
//!     -Wl,-rpath,$BUILD/bin -o /tmp/ref_logits
//! /tmp/ref_logits crates/ferrox-models/tests/fixtures/dots1_tiny.gguf 3 7 11 19 23 5
//! ```

mod common;
use common::assert_close;
use ferrox_core::cache::KvCache;
use ferrox_models::{Decoder, ModelConfig};

const FIXTURE: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/tests/fixtures/dots1_tiny.gguf"
);

const PROMPT: [usize; 6] = [3, 7, 11, 19, 23, 5];

/// llama.cpp's logits for `PROMPT`'s last position. See module docs.
const GOLDEN_LOGITS: [f32; 48] = [
    0.2556544,
    0.13536981,
    0.4295799,
    0.056047127,
    -0.124518335,
    -0.16960064,
    0.114657365,
    -0.1430278,
    -0.004434094,
    -0.14266315,
    -0.19511004,
    -0.30258057,
    0.37223065,
    0.052896023,
    -0.5035858,
    -0.273538,
    0.03588015,
    -0.040849388,
    0.24461555,
    0.055972166,
    -0.1508835,
    0.14803813,
    -0.25288546,
    0.2587794,
    -0.6169028,
    -0.022526622,
    0.023016624,
    -0.10334115,
    -0.23648755,
    0.4078294,
    -0.21243697,
    -0.20589492,
    0.03164079,
    0.25224513,
    -0.110857315,
    -0.06904118,
    0.120956406,
    0.37576866,
    -0.023103673,
    0.78746593,
    -0.35768974,
    -0.50862193,
    0.14170763,
    -0.13150944,
    -0.17099534,
    -0.06855504,
    0.5526021,
    0.24868289,
];

/// Float32 accumulation order differs between the two engines, so this
/// is a numeric-agreement tolerance, not a bit-exactness claim. Every
/// mutation in `routing_bias_golden_is_not_vacuous` moves the logits by
/// orders of magnitude more than this.
const TOL: f32 = 1e-6;

fn load() -> Decoder {
    let file = ferrox_gguf::GgufFile::open(FIXTURE).expect("fixture opens");
    let config = ModelConfig::from_gguf(&file).expect("fixture config parses");
    Decoder::from_gguf(FIXTURE, config).expect("fixture loads")
}

fn prefill(decoder: &Decoder) -> Vec<f32> {
    let mut caches: Vec<KvCache> = decoder.config.new_kv_caches();
    decoder.forward_batch_last(&PROMPT, 0, &mut caches)
}

/// The claim: ferrox's generic MoE graph with `exp_probs_b` agrees with
/// llama.cpp's.
#[test]
fn routing_bias_prefill_matches_llama_cpp() {
    assert_close(
        &prefill(&load()),
        &GOLDEN_LOGITS,
        TOL,
        "prefill (forward_batch_last)",
    );
}

/// The decode path routes per position through a different call site.
#[test]
fn routing_bias_decode_matches_llama_cpp() {
    let decoder = load();
    let mut caches: Vec<KvCache> = decoder.config.new_kv_caches();
    let mut logits = Vec::new();
    for (pos, &tok) in PROMPT.iter().enumerate() {
        logits = decoder.forward_token(tok, pos, &mut caches);
    }
    assert_close(&logits, &GOLDEN_LOGITS, TOL, "decode (forward_token)");
}

/// The continuous-batching path is the third copy of the same math.
#[test]
fn routing_bias_multi_seq_matches_llama_cpp() {
    let decoder = load();
    let mut caches: Vec<Vec<KvCache>> = vec![decoder.config.new_kv_caches()];
    let mut logits = Vec::new();
    for (pos, &tok) in PROMPT.iter().enumerate() {
        let out = decoder.forward_multi_seq(&[tok], &[pos], &mut caches);
        logits = out.into_iter().next().unwrap();
    }
    assert_close(&logits, &GOLDEN_LOGITS, TOL, "multi-seq");
}

/// What the loader decided, so a regression in a piece that is not
/// separately visible in the logits still names itself.
#[test]
fn the_loader_reads_the_bias_and_both_weight_hparams() {
    let decoder = load();
    // Leading dense layer carries no router and no bias.
    assert_eq!(decoder.config.n_dense_leading_layers, 1);
    assert!(decoder.layers[0].moe.exp_probs_bias.is_none());
    let bias = decoder.layers[1]
        .moe
        .exp_probs_bias
        .as_ref()
        .expect("blk.1 must carry exp_probs_b.bias");
    assert_eq!(bias.len(), decoder.config.moe.n_experts);
    assert!(
        bias.iter().any(|&b| b != 0.0),
        "a zero bias would make this test vacuous"
    );

    // `expert_weights_scale` / `expert_weights_norm` are read from the
    // file, not guessed from the architecture name.
    assert_eq!(decoder.config.moe.expert_weights_scale, 2.5);
    assert!(decoder.config.moe.norm_topk_prob);
    assert_eq!(
        decoder.config.best_effort_fields.len(),
        1,
        "nothing about this fixture should have been inferred: {:?}",
        decoder.config.best_effort_fields
    );
}

/// The bias must actually change which experts fire on this fixture,
/// otherwise the golden comparison would pass with the bias ignored and
/// prove nothing about the selection half of the port.
#[test]
fn the_bias_reorders_the_selection_on_this_fixture() {
    let decoder = load();
    let bias = decoder.layers[1].moe.exp_probs_bias.clone().unwrap();
    let n = decoder.config.moe.n_experts;
    let k = decoder.config.moe.n_experts_active;

    // A router-logit row taken from the fixture's own scale: the point
    // is only that `sigmoid(l)` and `sigmoid(l) + bias` rank differently.
    let logits: Vec<f32> = (0..n).map(|i| 0.2 * (i as f32) - 0.5).collect();
    let unbiased = ferrox_moe::route_top_k_biased(
        &logits,
        None,
        k,
        decoder.config.moe.gating,
        decoder.config.moe.norm_topk_prob,
        decoder.config.moe.expert_weights_scale,
    );
    let biased = ferrox_moe::route_top_k_biased(
        &logits,
        Some(&bias),
        k,
        decoder.config.moe.gating,
        decoder.config.moe.norm_topk_prob,
        decoder.config.moe.expert_weights_scale,
    );
    assert_ne!(
        unbiased.expert_ids, biased.expert_ids,
        "the fixture's bias must reorder the top-k, or the golden test is vacuous"
    );
}

/// Mutation check: the golden comparison must fail when the routing is
/// broken on purpose. Each of these is a term that was absent from
/// ferrox's generic MoE path before this work.
#[test]
fn routing_bias_golden_is_not_vacuous() {
    let baseline = prefill(&load());
    assert_close(&baseline, &GOLDEN_LOGITS, TOL, "baseline");

    // 1. Ignore the selection bias entirely — the pre-existing behaviour,
    //    and the one the tensor-consumption gate used to refuse.
    {
        let mut decoder = load();
        decoder.layers[1].moe.exp_probs_bias = None;
        let got = prefill(&decoder);
        let worst = got
            .iter()
            .zip(GOLDEN_LOGITS.iter())
            .map(|(a, b)| (a - b).abs())
            .fold(0f32, f32::max);
        assert!(
            worst > 1e-3,
            "dropping exp_probs_b must move the logits, got {worst}"
        );
    }

    // 2. Bias the combine weight as well as the selection — the
    //    plausible-but-wrong reading of `build_moe_ffn`.
    {
        let logits: Vec<f32> = vec![-0.4, 0.1, 0.7, -0.2, 0.3, 0.0];
        let bias: Vec<f32> = vec![0.5, -0.3, 0.2, 0.4, -0.1, 0.25];
        let correct = ferrox_moe::route_top_k_biased(
            &logits,
            Some(&bias),
            2,
            ferrox_moe::GatingFunction::Sigmoid,
            true,
            1.0,
        );
        let biased_logits: Vec<f32> = logits.iter().zip(&bias).map(|(l, b)| l + b).collect();
        let wrong = ferrox_moe::route_top_k_biased(
            &biased_logits,
            None,
            2,
            ferrox_moe::GatingFunction::Sigmoid,
            true,
            1.0,
        );
        assert_ne!(
            correct.weights, wrong.weights,
            "the bias must reach selection only, never the combine weight"
        );
    }

    // 3. Drop `expert_weights_scale`.
    {
        let mut decoder = load();
        decoder.config.moe.expert_weights_scale = 1.0;
        let got = prefill(&decoder);
        let worst = got
            .iter()
            .zip(GOLDEN_LOGITS.iter())
            .map(|(a, b)| (a - b).abs())
            .fold(0f32, f32::max);
        assert!(
            worst > 1e-3,
            "dropping expert_weights_scale must move the logits, got {worst}"
        );
    }

    // 4. Drop the renormalisation.
    {
        let mut decoder = load();
        decoder.config.moe.norm_topk_prob = false;
        let got = prefill(&decoder);
        let worst = got
            .iter()
            .zip(GOLDEN_LOGITS.iter())
            .map(|(a, b)| (a - b).abs())
            .fold(0f32, f32::max);
        assert!(
            worst > 1e-3,
            "dropping expert_weights_norm must move the logits, got {worst}"
        );
    }
}
