//! Qwen3-MoE graph coverage, checked against llama.cpp itself.
//!
//! `qwen3moe` is what Qwen3-30B-A3B and Qwen3-235B-A22B tag, so it is
//! one of the most-run MoE architectures on consumer hardware — and it
//! sat on ferrox's shared *generic* GQA path with nothing behind it but
//! the assumption that the path fits. This file is the evidence that
//! decides whether it belongs in
//! `ferrox_models::capability::AUDITED_GENERIC_GQA`.
//!
//! `tests/fixtures/qwen3moe_tiny.gguf` is a 2-layer, 32-wide, 6-expert
//! `qwen3moe` checkpoint generated by `scripts/make_qwen3moe_fixture.py`
//! (fixed seed, byte-stable). It is small but structurally complete
//! against `.scratch/llama.cpp/src/models/qwen3moe.cpp`:
//!
//! * per-head Q/K RMSNorm of length `head_dim`, applied **before** RoPE
//!   (qwen3moe.cpp:99,108);
//! * `head_dim * n_head != n_embd` (16 * 4 vs 32), so a decoder that
//!   derives `head_dim = n_embd / n_head` gets 8 and a non-square
//!   `attn_output`;
//! * GQA with `n_head_kv = 2 < n_head = 4`;
//! * NEOX RoPE (llama.cpp prints `rope type = 2` for this file);
//! * softmax gating with renormalised top-k weights, both llama.cpp
//!   literals at qwen3moe.cpp:141;
//! * `n_ff = 40 != n_ff_exp = 16`, so the experts must be sized from
//!   `expert_feed_forward_length`.
//!
//! `GOLDEN_LOGITS` was produced by running **llama.cpp's own** qwen3moe
//! implementation over that same file
//! (`scripts/gptoss_reference_logits.cpp`, linked against a real
//! `libllama`), not by re-reading a spec and not by ferrox checking
//! itself.
//!
//! Regenerating (both halves must be redone together if the fixture
//! changes):
//!
//! ```text
//! PYTHONPATH=$LLAMA/gguf-py python3 scripts/make_qwen3moe_fixture.py \
//!     crates/ferrox-models/tests/fixtures/qwen3moe_tiny.gguf
//! clang++ -std=c++17 -O2 scripts/gptoss_reference_logits.cpp \
//!     -I$LLAMA/include -I$LLAMA/ggml/include -L$BUILD/bin -lllama \
//!     -Wl,-rpath,$BUILD/bin -o /tmp/ref_logits
//! /tmp/ref_logits crates/ferrox-models/tests/fixtures/qwen3moe_tiny.gguf 3 7 11 19 23 5
//! ```

mod common;
use common::assert_close;
use ferrox_core::cache::KvCache;
use ferrox_models::capability::QkNormStyle;
use ferrox_models::{Decoder, ModelConfig};

const FIXTURE: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/tests/fixtures/qwen3moe_tiny.gguf"
);

const PROMPT: [usize; 6] = [3, 7, 11, 19, 23, 5];

/// llama.cpp's logits for `PROMPT`'s last position. See module docs.
const GOLDEN_LOGITS: [f32; 48] = [
    -0.5604392,
    0.37787852,
    0.28852117,
    -0.09789829,
    -0.48475564,
    0.07075651,
    0.465528,
    0.5373838,
    -0.11255781,
    -0.22411966,
    0.07069388,
    -0.34745902,
    -0.21218541,
    0.5015559,
    -0.22569102,
    0.26042414,
    0.1846947,
    -0.62299764,
    0.53317493,
    0.09572075,
    -0.52854526,
    0.041242458,
    0.22131333,
    -0.02710408,
    -0.4266994,
    -0.28987896,
    0.27744383,
    0.09985334,
    -0.09879099,
    0.0514909,
    -0.15669407,
    0.4099903,
    0.04141575,
    0.0480583,
    0.20120946,
    -0.22090337,
    -0.50722754,
    0.5773386,
    -0.38261855,
    0.43768734,
    -0.023896411,
    0.57459176,
    -0.63180256,
    0.28280866,
    -0.43498603,
    -0.5719695,
    0.13300264,
    -0.04597807,
];

/// Float32 accumulation order differs between the two engines (ggml
/// blocks its matmuls; ferrox does not), so this is a numeric-agreement
/// tolerance, not a bit-exactness claim. Every mutation in
/// `qwen3moe_golden_is_not_vacuous` moves the logits by orders of
/// magnitude more than this.
const TOL: f32 = 1e-6;

fn load() -> Decoder {
    let file = ferrox_gguf::GgufFile::open(FIXTURE).expect("fixture opens");
    let config = ModelConfig::from_gguf(&file).expect("fixture config parses");
    Decoder::from_gguf(FIXTURE, config).expect("fixture loads")
}

fn caches(decoder: &Decoder) -> Vec<KvCache> {
    decoder.config.new_kv_caches()
}

fn prefill(decoder: &Decoder) -> Vec<f32> {
    let mut kv = caches(decoder);
    decoder.forward_batch_last(&PROMPT, 0, &mut kv)
}

/// The claim: ferrox's generic decoder computes Qwen3-MoE the way
/// llama.cpp does.
#[test]
fn qwen3moe_prefill_matches_llama_cpp() {
    assert_close(
        &prefill(&load()),
        &GOLDEN_LOGITS,
        TOL,
        "prefill (forward_batch_last)",
    );
}

/// The decode path routes per position through a different call site.
#[test]
fn qwen3moe_decode_matches_llama_cpp() {
    let decoder = load();
    let mut kv = caches(&decoder);
    let mut logits = Vec::new();
    for (pos, &tok) in PROMPT.iter().enumerate() {
        logits = decoder.forward_token(tok, pos, &mut kv);
    }
    assert_close(&logits, &GOLDEN_LOGITS, TOL, "decode (forward_token)");
}

/// The continuous-batching path is the third copy of the same math.
#[test]
fn qwen3moe_multi_seq_matches_llama_cpp() {
    let decoder = load();
    let mut kv = vec![caches(&decoder)];
    let mut logits = Vec::new();
    for (pos, &tok) in PROMPT.iter().enumerate() {
        let out = decoder.forward_multi_seq(&[tok], &[pos], &mut kv);
        logits = out.into_iter().next().unwrap();
    }
    assert_close(&logits, &GOLDEN_LOGITS, TOL, "multi-seq");
}

/// What the loader decided, so a regression in a piece the logits alone
/// would not name still names itself.
#[test]
fn the_loader_reads_qwen3moes_own_shapes_and_routing_literals() {
    let decoder = load();

    // `head_dim` comes from `qwen3moe.attention.key_length`, NOT from
    // `n_embd / n_head` — which would be 8 here, and 64 instead of 128
    // on a real Qwen3-30B-A3B.
    assert_eq!(decoder.config.head_dim, 16);
    assert_eq!(decoder.config.hidden_dim, 32);
    assert_eq!(decoder.config.n_heads, 4);
    assert_eq!(decoder.config.n_kv_heads, 2);

    // Per-head QK norm: one `head_dim`-long weight, not a whole-vector
    // one of width `n_head * head_dim`.
    assert_eq!(decoder.config.qk_norm_style, QkNormStyle::PerHead);
    for (il, layer) in decoder.layers.iter().enumerate() {
        let q = layer
            .attn
            .q_norm
            .as_ref()
            .unwrap_or_else(|| panic!("blk.{il} must carry attn_q_norm"));
        let k = layer
            .attn
            .k_norm
            .as_ref()
            .unwrap_or_else(|| panic!("blk.{il} must carry attn_k_norm"));
        assert_eq!(q.len(), decoder.config.head_dim);
        assert_eq!(k.len(), decoder.config.head_dim);
    }

    // qwen3moe.cpp:141 passes `norm_w = true` and
    // `LLAMA_EXPERT_GATING_FUNC_TYPE_SOFTMAX` as literals, and its
    // `load_arch_hparams` reads none of `expert_weights_norm`,
    // `expert_gating_func` or `expert_weights_scale` from the file.
    assert_eq!(decoder.config.moe.n_experts, 6);
    assert_eq!(decoder.config.moe.n_experts_active, 2);
    assert!(decoder.config.moe.norm_topk_prob);
    assert_eq!(decoder.config.moe.expert_weights_scale, 1.0);
    // No shared expert and no selection bias on this architecture.
    assert_eq!(decoder.config.moe.n_shared_experts, 0);
    for layer in &decoder.layers {
        assert!(layer.moe.exp_probs_bias.is_none());
    }
    // Experts are sized from `expert_feed_forward_length` (16), not
    // from `feed_forward_length` (40).
    assert_eq!(decoder.config.moe.expert_ffn_dim, 16);
}

/// The golden comparison must fail when the graph is broken on purpose.
/// Each mutation below is a term Qwen3-MoE has and plain llama does not,
/// i.e. exactly what "the generic path fits this architecture" is a
/// claim about.
#[test]
fn qwen3moe_golden_is_not_vacuous() {
    let worst = |got: &[f32]| {
        got.iter()
            .zip(GOLDEN_LOGITS.iter())
            .map(|(a, b)| (a - b).abs())
            .fold(0f32, f32::max)
    };

    assert_close(&prefill(&load()), &GOLDEN_LOGITS, TOL, "baseline");

    // 1. Q/K norm applied over the whole projection instead of per head
    //    — the OLMoE reading of the same two tensors. The weights are
    //    tiled to the full projection width first, so the *only*
    //    difference from the baseline is where the RMS is taken: across
    //    all four heads at once instead of within each.
    {
        let mut decoder = load();
        let head_dim = decoder.config.head_dim;
        let n_heads = decoder.config.n_heads;
        let n_kv = decoder.config.n_kv_heads;
        decoder.config.qk_norm_style = QkNormStyle::WholeVector;
        for layer in &mut decoder.layers {
            let tile = |w: &Vec<f32>, reps: usize| -> Vec<f32> {
                (0..reps * head_dim).map(|i| w[i % head_dim]).collect()
            };
            layer.attn.q_norm = layer.attn.q_norm.as_ref().map(|w| tile(w, n_heads));
            layer.attn.k_norm = layer.attn.k_norm.as_ref().map(|w| tile(w, n_kv));
        }
        let w = worst(&prefill(&decoder));
        assert!(
            w > 1e-3,
            "whole-vector QK norm must not agree with per-head, got {w}"
        );
    }

    // 2. Drop the QK norm entirely — plain Qwen2 / llama attention.
    {
        let mut decoder = load();
        for layer in &mut decoder.layers {
            layer.attn.q_norm = None;
            layer.attn.k_norm = None;
        }
        let w = worst(&prefill(&decoder));
        assert!(
            w > 1e-3,
            "dropping attn_q/k_norm must move the logits, got {w}"
        );
    }

    // 3. Drop the top-k renormalisation. qwen3moe hardcodes `norm_w =
    //    true`; its sibling `qwen2moe` hardcodes `false`, so this is a
    //    live confusion and not a hypothetical one.
    {
        let mut decoder = load();
        decoder.config.moe.norm_topk_prob = false;
        let w = worst(&prefill(&decoder));
        assert!(
            w > 1e-3,
            "dropping the top-k renormalisation must move the logits, got {w}"
        );
    }

    // 4. Sigmoid gating instead of softmax.
    {
        let mut decoder = load();
        decoder.config.moe.gating = ferrox_moe::GatingFunction::Sigmoid;
        let w = worst(&prefill(&decoder));
        assert!(
            w > 1e-3,
            "sigmoid gating must not agree with softmax, got {w}"
        );
    }

    // 5. Route to every expert's nearest neighbour instead of the
    //    selected one — proves the expert *identity* is in the answer,
    //    not just the weights.
    {
        let mut decoder = load();
        let n = decoder.config.moe.n_experts;
        decoder.config.moe.n_experts_active = n;
        let w = worst(&prefill(&decoder));
        assert!(
            w > 1e-3,
            "using all experts must not agree with top-2, got {w}"
        );
    }
}
